export enum Artist {
  albrechtDurer = 'Albrecht_Durer',
  borisKustodiev = 'Boris_Kustodiev',
  camillePissarro = 'Camille_Pissarro',
  childeHassam = 'Childe_Hassam',
  claudeMonet = 'Claude_Monet',
  edgarDegas = 'Edgar_Degas',
  eugeneBoudin = 'Eugene_Boudin',
  gustaveDore = 'Gustave_Dore',
  ilyaRepin = 'Ilya_Repin',
  ivanAivazovsky = 'Ivan_Aivazovsky',
  ivanShishkin = 'Ivan_Shishkin',
  johnSingerSargent = 'John_Singer_Sargent',
  marcChagall = 'Marc_Chagall',
  martirosSaryan = 'Martiros_Saryan',
  nicholasRoerich = 'Nicholas_Roerich',
  pabloPicasso = 'Pablo_Picasso',
  paulCezanne = 'Paul_Cezanne',
  pierreAugusteRenoir = 'Pierre_Auguste_Renoir',
  pyotrKonchalovsky = 'Pyotr_Konchalovsky',
  raphaelKirchner = 'Raphael_Kirchner',
  rembrandt = 'Rembrandt',
  salvadorDali = 'Salvador_Dali',
  vincentVanGogh = 'Vincent_van_Gogh',
  alfonsWalde = 'Alfons_Walde'
}
